[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["Kross07 <65046270+Kross07@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
